name: Build Docker Image
on:
  workflow_call:
  push:
    branches:
      - personal

jobs:
  build-binary:
    uses: ./.github/workflows/docker-build-static-personal.yml

  build-docker-image:
    needs: [build-binary]
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        base: [debian]
        include:
          - base: debian
            platforms: linux/amd64,linux/arm64

    steps:
      - name: fetch repo
        uses: actions/checkout@v3.3.0
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin

      - name: Download llap ui artifacts
        uses: actions/download-artifact@v3
        with:
          name: ui
          path: web

      - name: setup qemu
        uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: metaid
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            martadinata666/lldap
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

