name: build freebsd binary

on:
  workflow_call:

jobs:
  build-bin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-freebsd]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
                ~/.cargo/bin/
                ~/.cargo/registry/index/
                ~/.cargo/registry/cache/
                ~/.cargo/git/db/
                target/
          key: lldap-bin-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
              lldap-bin-${{ matrix.target }}-
      - name: Install podman
        run: |
             sudo apt update
             sudo apt install -y podman
      - name: Use cross?
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Build with cross
        run: /home/runner/.cargo/bin/cross build --release --target x86_64-unknown-freebsd -p lldap -p lldap_migration_tool -p lldap_set_password
      #- name: compile ${{ matrix.target }}
      #  run: cargo build --target=${{ matrix.target }} --release -p lldap
      - name: check path
        run: ls -alr target/release

      - name: upload ${{ matrix.target}} lldap artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target}}-lldap-bin
          path: target/${{ matrix.target }}/release/lldap

      - name: upload ${{ matrix.target }} migration tool artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-migration-tool-bin
          path: target/${{ matrix.target }}/release/lldap_migration_tool

      - name: upload ${{ matrix.target }}-set-password-bin
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-lldap-set-password-bin
          path: target/${{ matrix.target }}/release/lldap_set_password
