name: Database Init Test
on:
  workflow_call:
  push:
    branches:
      - personal

jobs:
  build-binary:
    uses: ./.github/workflows/build-binary.yml

  build-ui:
    uses: ./github/.workflows/build-ui.yml

  lldap-init-test:
    needs: [build-binary]
    name: LLDAP database init test
    runs-on: ubuntu-latest
    services:
        mariadb:
          image: mariadb:latest
          ports:
            - 3306:3306
          env:
            MYSQL_USER: lldapuser
            MYSQL_PASSWORD: lldappass
            MYSQL_DATABASE: lldap
            MYSQL_ROOT_PASSWORD: rootpass

        postgresql:
           image: postgres:latest
           ports:
             - 5432:5432
           env:
             POSTGRES_USER: lldapuser
             POSTGRES_PASSWORD: lldappass
             POSTGRES_DB: lldap

    steps:
       - name: Download All Artifacts
         uses: actions/download-artifact@v3
         with:
           path: bin/
       - name: Set executables
         run: chmod +x bin/*/lldap
       - name: run lldap with postgres DB
         run: |
              bin/x86_64-unknown-linux-musl-lldap-bin/lldap run &
              sleep 10s
              bin/x86_64-unknown-linux-musl-lldap-bin/lldap healthcheck
         env:
           LLDAP_database_url: postgres://lldapuser:lldappass@localhost/lldap
           LLDAP_ldap_port: 3890
           LLDAP_http_port: 17170


       - name: run lldap with mariadb DB (MySQL Compatible)
         run: |
              bin/x86_64-unknown-linux-musl-lldap-bin/lldap run &
              sleep 10s
              bin/x86_64-unknown-linux-musl-lldap-bin/lldap healthcheck
         env:
           LLDAP_database_url: mysql://lldapuser:lldappass@localhost/lldap
           LLDAP_ldap_port: 3891
           LLDAP_http_port: 17171

