name: Docker Static Personal

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

# In total 5 jobs, all the jobs are containerized
# ---

#######################################################################################
# GitHub actions randomly timeout when downloading musl-gcc                           #
# Using lldap dev image based on https://hub.docker.com/_/rust and musl-gcc bundled   #
# Look into .github/workflows/Dockerfile.dev for development image details            #
#######################################################################################

# build-ui , create/compile the web
### install wasm
### install rollup
### run app/build.sh
### upload artifacts

# builds-armhf, build-aarch64, build-amd64 create binary for respective arch
### Add non-native architecture dpkg --add-architecture XXX
### Install dev tool gcc g++, etc. per respective arch
### Cargo build
### Upload artifacts

## the CARGO_ env
#CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
# This will determine which architecture lib will be used.

# build-ui,builds-armhf, build-aarch64, build-amd64 will upload artifacts will be used next job
# build-docker-image job will fetch artifacts and run Dockerfile.ci then push the image.

# cache based on Cargo.lock

jobs:
  build-ui:
    runs-on: ubuntu-latest
    container:
      image: martadinata666/rust:latest
      options: --user root
    steps:
      - name: Pull from git
        run: |
              sudo apt update
              sudo apt -y install gzip
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            cargo/registry/index
            cargo/registry/cache
            cargo/git/db
            target
          key: lldap-ui-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            lldap-ui-
      - name: install wasm-pack via cargo
        run: |
             cargo install wasm-pack
             rustup target add wasm32-unknown-unknown
      - name: build frontend
        run: ./app/build.sh
      - name: check path
        run: ls -al app/
      - name: upload ui artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ui
          path: app/

  build-bin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [armv7-unknown-linux-gnueabihf,aarch64-unknown-linux-musl,x86_64-unknown-linux-musl]
    container:
      image: martadinata666/rust:latest
      options: --user root
      env:
        CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-musl-gcc
        CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER: x86_64-linux-musl-gcc
        CARGO_TERM_COLOR: always
        RUSTFLAGS: -Ctarget-feature=+crt-static
        CARGO_HOME: ${GITHUB_WORKSPACE}/.cargo
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            .cargo/registry/index
            .cargo/registry/cache
            .cargo/git/db
            target/
          key: lldap-bin-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            lldap-bin-${{ matrix.target }}-
      - name: show my env
        run: env
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: compile ${{ matrix.target }}
        run: cargo build --target=${{ matrix.target }} --release -p lldap -p migration-tool
      - name: check path
        run: ls -al target/release
      - name: upload ${{ matrix.target}} lldap artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target}}-lldap-bin
          path: target/${{ matrix.target }}/release/lldap
      - name: upload ${{ matrix.target }} migration tool artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-migration-tool-bin
          path: target/${{ matrix.target }}/release/migration-tool

