name: main
on:
  workflow_call:
  push:
    branches:
      - personal

jobs:
  build-linux-binary:
    uses: ./.github/workflows/build-linux-binary.yml
    
  build-freebsd-binary:
    uses: ./.github/workflows/build-freebsd-binary.yml  

  build-ui:
    uses: ./.github/workflows/build-ui.yml

  lldap-init-test:
    needs: [build-ui,build-linux-binary]
    uses: ./.github/workflows/database-init-test.yml

  lldap-mariadb-migration-test:
    needs: [build-linux-binary]
    uses: ./.github/workflows/database-mariadb-migration-test.yml

  lldap-postgress-migration-test:
    needs: [build-linux-binary]
    uses: ./.github/workflows/database-postgres-migration-test.yml
