name: Database Init Test
on:
  workflow_call:
  push:
    branches:
      - personal

jobs:
  build-binary:
    uses: ./.github/workflows/build-binary.yml

  build-ui:
    uses: ./.github/workflows/build-ui.yml

  lldap-init-test:
    needs: [build-ui,build-binary]
    uses: ./.github/workflows/database-init-test.yml

  lldap-mariadb-migration-test:
    needs: [build-binary]
    uses: ./.github/workflows/database-mariadb-migration-test.yml

  lldap-postgress-migration-test:
    needs: [build-binary]
    uses: ./.github/workflows/database-postgres-migration-test.yml